MENT-815 node restart overlaps with earlier still ongoing SST process
codership/mariadb-server pull request #191
Opened 2020-11-12 19:40 UTC by sjaakola

In galera.galera_nbo_sst_slave test node restart can happen too soon, when earlier SST joiner process is still active in the node.
The fix in this pull request, does an additional check in mysqld startup phase to find out if SST progress file (sst_in_progress) is in mysql data directory.
(wsrep replication writes this file when SST begins, and removes the file when SST is finally over).
If SST progress file is found, mysqld startup phase will poll for 10 secs to see if the file is removed. If SST file remains still after this 10 sec polling, mysqld startup fails with error.
It could be that SST process has failed brutally and could not complete the cleanup phase, leaving a stale SST progress file behind.

2020-11-13 13:04 UTC, temeo requested changes
This change relies on SST script managing `sst_in_progress` file in data directory, which sounds quite a strong assumption. I don't have any better alternative to suggest though...

I'd suggest that the code to check the file would be moved into `wsrep_sst.cc` and the assumption about the `sst_in_progress` file existence would be documented there somehow.

2020-11-17 07:52 UTC, sjaakola commented
SST progress file could be defined in mysqld side (wsrep_sst.cc) and pushed for SST scripts as argument in the SST script API. And wsrep_sst_common.sh would have the responsibility to write and remove the SST progress file. 
Currently SST progress file is empty, but wsrep_sst_common.sh could write the PID of SST process in the file. With this design, it would be possible to detect in mysqld startup phase, if SST from previous mysqld startup is still ongoing.

2020-11-17 16:03 UTC, sjaakola commented
Pushed a fix according to Teemu's review. Also refactored to hand out the SST progress file name from mariadbd to SST script through SST scripting API. With this, the SST script and mariadbd should be using same SST progress file.

However, while doing this, I'm also losing fate if we can effectively monitor all SST method executions from within mariadbd. It might be better just to sort out lingering rsync process issue, which bothers rsync SST separately in wsrep_sst_rsync.sh script. And if other SST methods show similar issues, they should be fixed in each SST method scripting. 

I have prepared another PR for this ment-815 plan B fix.

2020-11-18 15:59 UTC, sjaakola commented
closing PR for MDEV-24097 will fix this also

2020-11-18 15:59 UTC, closed without merging