MDEV-22227 Assertion `state_ == s_exec' failed in wsrep::client_state…
codership/mariadb-server pull request #216
Opened 2021-04-26 09:21 UTC by mkaruza

…::start_transaction

Removed redundant code for BF abort transaction in `thr_lock.cc`. Moved TOI
after opening locking tables.

2021-04-26 10:30 UTC, sjaakola requested changes
TOI replication has to happen before MDL locking
Timeouts during DDL processed as TOI should be disabled

2021-04-26 10:30 UTC, sjaakola commented on sql/sql_view.cc
> +
TOI replication should happen before open_and_lock_tables(), so better move this back to original position

2021-04-26 10:30 UTC, sjaakola commented on sql/sql_view.cc
> +
To handle timeouts during open_and_lock_tables(), we should disable timeouts for TOI replicated sessions

2021-04-27 15:55 UTC, sjaakola approved these changes
this is good now. Technically it is not yet exactly deterministic, because there is still a timeout, but good enough approximation, as LONG_TIMEOUT gives one year waiting time

2021-04-27 17:56 UTC, mkaruza commented
Closing and opening against Mariadb

2021-04-27 17:56 UTC, closed without merging