MENT-425 Implement a method to add IPs to allowlist for Galera Cluste…
codership/mariadb-server pull request #243
Opened 2021-11-29 08:12 UTC by mkaruza

…r node addresses that can make SST/IST requests

2021-11-30 09:54 UTC, sciascid reviewed
This is a request for clarification: the whitelist table is replicated, right?
And if so, is it possible that the contents of the whitelist table may diverge on different nodes, if nodes have configured their wsrep_whitelist variable differently?

So for example, consider this scenario:
Inittially you start one node1, which has ip-x in wsrep_whitelist variable. Then node2 joins, and it has ip-x and ip-y, in its wsrep_whitelist variable.
What is the contents of the whitelist table in the two nodes?

2021-12-03 07:51 UTC, mkaruza commented
@sciascid you are right about this, on node2 we would receive all information from donor node, but we are going to append missing allowlist entries from `wsrep_allowlist` without replication. I think approach for this is that *only* node which bootstrapped cluster should set initial allowlist. Comments about this ?

2021-12-06 10:58 UTC, sciascid requested changes
Add a test that shows only bootstrap server adds entries from allowlist variable, while other nodes ignore the variable.

2021-12-06 10:58 UTC, sciascid commented on sql/wsrep_mysqld.cc
> +      (strlen(wsrep_cluster_address) == 8) &&
This call to `strlen()` seems unnecessary. 
Consider removing it.

2021-12-06 11:18 UTC, sciascid commented on sql/wsrep_mysqld.cc
> +      (strlen(wsrep_cluster_address) == 8) &&
Disregard my comment above.

2021-12-06 12:02 UTC, sciascid approved these changes
Looks good now

2021-12-13 11:34 UTC, mkaruza commented
Closed and opened against MariaDB

2021-12-13 11:34 UTC, closed without merging