MDEV-27568 Parallel async replication hangs on a Galera node
codership/mariadb-server pull request #257
Opened 2022-02-16 14:09 UTC by mkaruza

Using parallel slave applying can cause deadlock between between DDL and
other events. GTID with lower seqno can be blocked in galera when node
entered TOI mode, but DDL GTID which has higher node can be blocked
before previous GTIDs are applied locally.

Fix is to check prior commits before entering TOI.

2022-02-21 10:58 UTC, sjaakola requested changes

2022-02-21 10:58 UTC, sjaakola commented on sql/wsrep_mysqld.cc
> +    return -1;
should this be WSREP_WARN instead? This happens only if wait_for_prior_commit() has failed, after all

2022-02-21 10:58 UTC, sjaakola commented on sql/wsrep_mysqld.cc
> +{
the name of the method is a bit misleading, as it is the parallel slave who is waiting. I suggest to change to:
wsrep_parallel_slave_wait_for prior_commit()

2022-02-21 13:13 UTC, sjaakola approved these changes
looks good

2022-02-23 10:14 UTC, mkaruza commented
Closing, opening against Mariadb

2022-02-23 10:14 UTC, closed without merging