MDEV-29512 deadlock between commit monitor and THD::LOCK_thd_data mutex
codership/mariadb-server pull request #274
Opened 2022-11-08 14:52 UTC by sjaakola

This commit contains only a mtr test for reproducing the issue in MDEV-29512 The actual fix will be pushed in wsrep-lib repository

The hanging in MDEV-29512 happens when binlog purging is attempted, and there is one local BF aborted transaction waiting for commit monitor.

The test will launch two node cluster and enable binlogging with expire log days, to force binlog purging to happen.
A local transaction is executed so that will become BF abort victim, and has advanced to replication stage waiting for commit monitor for final cleanup (to mark position in innodb) after that, applier is released to complete the BF abort and due to binlog configuration, starting the binlog purging. This is where the hanging would occur, if code is buggy

2022-11-08 16:12 UTC, temeo requested changes
This PR should also update wsrep-lib position. The new test `galera_MDEV-29512` hangs in Jenkins.

2022-11-08 16:12 UTC, temeo commented on mysql-test/suite/galera/t/galera_MDEV-29512.test
> +--source include/galera_clear_sync_point.inc
This sync point clearing is redundant (and maybe harmful), sync point is already cleared above.

2022-11-09 09:11 UTC, temeo approved these changes
Looks good now.

2022-11-09 11:01 UTC, sjaakola commented
closing and submitting to MariaDB

2022-11-09 11:01 UTC, closed without merging